name: canonization
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm

  - pip:
      - torch
      - torchvision
      - torchaudio
      - torch-geometric
      - hilbertcurve